[project]
site_url = "nipahbox.com"
site_name = "Nipahbox"
site_description = "Nipahbox"
site_author = "eg"

copyright = "Copyright &copy; 2026 Nipahbox"

repo_url = "https://github.com/Nipahbox/"
repo_name = "Nipahbox"
edit_uri = "nipahbox.com/edit/main/docs/"

nav = [
  { "Buyurmaz mısınız?" = [
    "index.md"
  ] },
  { "Fata Morgana" = [
  { "Giriş" = [
    { "Fata Morgana hakkında" = "fatamorgana/index.md" },
  ] },
  { "Çeviri" = [
    { "Çeviri Kurulumu" = "fatamorgana/kurulum.md" },
  ] },
    { "Daha fazla bilgi" = [
    "fatamorgana/yazar.md",
    "fatamorgana/NOVECT.md",
    ] },
 ] },
 { "Hakkımızda" = [
  "hakkimizda.md" ] },
]

extra_css = [
  "stylesheets/extra.css",
  "stylesheets/admonition.css"
]
extra_javascript = [
    "javascripts/extra.js",
    "javascripts/permalink.js"
]

[project.theme]
custom_dir = "overrides"
favicon = "../images/nipahbox-favicon.webp"
language = "tr"
features = [
  "announce.dismiss",
  # "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  "navigation.expand",
  "navigation.footer",
  # "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

logo = "../images/nipahbox-logo.svg"

[project.theme.icon]
repo = "fontawesome/brands/github"

# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/Nipahbox"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Nipahbox"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
zensical.extensions.glightbox = {
  auto_themed = true,
  auto_caption = true,
  skip_classes = ["no-lightbox"]
}
toc = {
  permalink = "Ω",
  title = "Bu sayfadakiler",
  permalink_title = "Bu bölümün bağlantısını kopyala",
  slugify.object = "pymdownx.slugs.slugify",
  slugify.kwds.case = "lower",
  toc_depth = 5
}
pymdownx.arithmatex = {
  generic = true
}
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji = {
  emoji_generator = "zensical.extensions.emoji.to_svg",
  emoji_index = "zensical.extensions.emoji.twemoji",
}
pymdownx.highlight = {
  anchor_linenums = true,
  line_spans = "__span",
  pygments_lang_class = true,
}
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets = {
#   base_path = "includes",
# }
pymdownx.superfences = {
  custom_fences = [
    {
      name = "mermaid",
      class = "mermaid",
      format = "pymdownx.superfences.fence_code_format",
    },
  ],
}
pymdownx.tabbed = {
  alternate_style = true,
  combine_header_slug = true
}
pymdownx.tasklist = {
  custom_checkbox = true
}
pymdownx.tilde = {}

[project.extra.status]
new = "Yeni eklendi"
deprecated = "Kullanımdan Kaldırıldı"
